//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISTURLIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ID_address { get; set; }
        public string City { get; set; }
        public string GRN { get; set; }
        public System.DateTime Date_USRLE { get; set; }
        public string Address1 { get; set; }

        public string Dategrn
        {
            get
            {
                string _Dategrn = GRN + " " + Date_USRLE;
                return _Dategrn;
            }
        }

        public virtual Organizations Organizations { get; set; }
    }
}
