//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISTURLIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capital
    {
        public int ID_capital { get; set; }
        public string View { get; set; }
        public decimal Size__in_rub_ { get; set; }
    
        public virtual Organizations Organizations { get; set; }
    }
}
