//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISTURLIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inactive_organizations
    {
        public int ID_inactive { get; set; }
        public int Organizations { get; set; }
        public string Reason { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Organizations Organizations1 { get; set; }
    }
}
