//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISTURLIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Legal_entity
    {
        public int ID_legal_entity { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string INN { get; set; }
        public string Post { get; set; }

        public string Allname
        {
            get
            {
                string _Allname = Lastname + " " + Name + " " + Patronymic;
                return _Allname;
            }
        }

        public virtual Organizations Organizations { get; set; }
    }
}
