//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISTURLIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organizations()
        {
            this.Inactive_organizations = new HashSet<Inactive_organizations>();
        }
    
        public int ID_organizations { get; set; }
        public string Full_name { get; set; }
        public string Abbreviated_name { get; set; }
        public string GRN { get; set; }
        public System.DateTime Date_USRLE { get; set; }
        public int Type_organizations { get; set; }
        public int Registration_authority { get; set; }
        public int Status_organizations { get; set; }

        public string Dategrn
        {
            get
            {
                string _Dategrn = GRN + " " + Date_USRLE;
                return _Dategrn;
            }
        }

        public virtual Address Address { get; set; }
        public virtual Capital Capital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inactive_organizations> Inactive_organizations { get; set; }
        public virtual Legal_entity Legal_entity { get; set; }
        public virtual Registration_authority Registration_authority1 { get; set; }
        public virtual Status_organizations Status_organizations1 { get; set; }
        public virtual Type_organization_ Type_organization_ { get; set; }
        public virtual Registration_information Registration_information { get; set; }
        public virtual Тax_accounting Тax_accounting { get; set; }
    }
}
