//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LISTURLIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_information
    {
        public int ID_registrations { get; set; }
        public string Мethod_education { get; set; }
        public string OGRN { get; set; }
        public System.DateTime Date { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
    
        public virtual Organizations Organizations { get; set; }
    }
}
